{% set name = "meningotype" %}
{% set version = "0.8.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MDU-PHL/meningotype/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6b9717d19b4ae8f3002fefdd602448a7754cad365042d92650ed3be012f05ef2

build:
  number: 0
  noarch: python
  entry_points:
    - meningotype=meningotype.meningotype:main
  run_exports:
    - {{ pin_subpackage('meningotype', max_pin="x") }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.12
  run:
    - python >=3.12
    - mlst
    - blast
    - ispcr

test:
  imports:
    - meningotype
  commands:
    - pip check
    - meningotype --help
    - meningotype --test
  requires:
    - pip

about:
  home: https://github.com/MDU-PHL/meningotype
  summary: In silico serotyping and finetyping (porA and fetA) of Neisseria meningitidis
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersgs
